# FTEmulator - FTEmulator is a high-performance stock market investment simulator designed with extreme technical efficiency
# Copyright (C) 2025-2025 Álex Frías (alexwebdev05)
# Licensed under AGPL-3.0 - see LICENSE file
# Commercial licensing: alexwebdev05@proton.me | GitHub: https://github.com/alexwebdev05
apiVersion: batch/v1
kind: Job
metadata:
  name: api-update-job-c9131e7
  namespace: api
spec:
  ttlSecondsAfterFinished: 200
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: api-update-sa
      restartPolicy: OnFailure
      initContainers:
        - name: git-clone
          image: alpine/git:2.49.0
          command: ["/bin/sh", "-c"]
          args: 
            - |
              rm -rf /repo/*
              mkdir -p /repo
              cd /repo
              git clone --depth 1 https://github.com/FTEmulator/FTEmulator-api .
          volumeMounts:
            - name: repo-volume
              mountPath: /repo
      containers:
        - name: sync
          image: "gradle:8.7.0-jdk21"
          command: ["/bin/sh", "-c"]
          args:
            - |
              rm -rf /mnt/api/*
              cd /repo
              chmod +x gradlew
              ./gradlew bootJar
              cp -r ./build/libs/*.jar /mnt/api/app.jar
              chmod +x /mnt/api/app.jar
              echo "La API se actualizó correctamente. Reiniciando..."
              kubectl rollout restart deployment api -n api
          volumeMounts:
            - name: api-volume
              mountPath: /mnt/api/
            - name: repo-volume
              mountPath: /repo
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: api-pvc
        - name: repo-volume
          emptyDir: {}
